version: "3.8"

services:
  bot:
    build: .
    container_name: venom_bot
    volumes:
      - .:/app
    working_dir: /app
    command: python bot.py
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
